name: 'Beta package updater'
description: 'Update the current package version with the build number'
author: 'Elio Struyf'
branding:
  icon: package
  color: red
inputs:
  build-id:
    description: 'Build ID'
    required: true
  path:
    description: 'Path of the package.json file'
    required: true
    default: 'package.json'

  # Extra parameters
  append-or-replace:
    description: 'Append the build ID to the version'
    required: true
    default: 'replace'
  preview:
    description: 'Sets the preview property'
    required: false
  name:
    description: 'Sets the name property'
    required: false
  display-name:
    description: 'Sets the displayName property'
    required: false
  description:
    description: 'Sets the description property'
    required: false
  icon:
    description: 'Sets the icon property'
    required: false
  homepage:
    description: 'Sets the homepage property'
    required: false
    
outputs:
  version:
    description: 'The new version ID'
runs:
  using: node20
  main: 'out/index.js'
